name: Crystal CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: shards install
    # - name: Run tests
    #   run: crystal spec
    - name: Build docs
      run: crystal docs

    - name: Install rsync
      run:         apt-get update && apt-get install -y rsync
    - name: Deploy docs
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs